version: '3.8'

networks:
  default:

services:
  db_dev:
    image: mysql:5.7.16
    container_name: goonies
    ports:
      - "3306:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: goonies