spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/goonies?autoreconnect=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  session:
    store-type: jdbc
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

