DROP TABLE IF EXISTS `review`;
DROP TABLE IF EXISTS `movie_genre`;
DROP TABLE IF EXISTS `movie`;
DROP TABLE IF EXISTS `genre`;
DROP TABLE IF EXISTS `country`;
DROP TABLE IF EXISTS `user_role`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `role`;